deepmodeling/dpdata

- dpdata/lammps/dump.py
I added a aux function to read fractional coords from lammps dump file in case it does not dump normal coordinates. The relation between normal coords and fractional coords follows [wikipedia](https://en.wikipedia.org/wiki/Fractional_coordinates).
> add function to handle fractional coordinates in lammps dump file

- dpdata/vasp/outcar.py
- tests/poscars/OUTCAR.ch4.1step
- tests/poscars/OUTCAR.ch4.unconverged
- tests/test_vasp_unconverged_outcar.py
Unit test of test_vasp_outcar.py is done.
> Select frames which are convergent in SC-calculatio of VASP

- dpdata/system.py
This commit allows that the system to be appended or the system to append is non-converged, which has an empty data.
> allow a non-converged system to append

- dpdata/gaussian/log.py
This PR fixes a bug, which would read coordinates repeatedly from Gaussian output when coordinates appear for multiple times.
> prevent to read coordinates repeatedly from Gaussian output

- dpdata/__init__.py
- dpdata/deepmd/comp.py
- dpdata/system.py
- tests/gaussian/methane_reordered.gaussianlog
- tests/gaussian/methane_sub.gaussianlog
- tests/test_multisystems.py
- tests/test_system_append.py
- Add a property `formula` for class `System`, which returns the chemical formula like `C3H4O6`
- Add a class called `MultiSystems`, which contains systems with different formula
- init: `systems = MultiSystems(system1, system2, system3)`
- property: `systems.systems`: a dict contains systems with different formula, like `systems['C1H4']`
- function:
- `append`: append a `System` to `MultiSystems`
- `to_deepmd_raw`, `to_deepmd_npy`: generate a folder containing folders for different systems
- Try to sort `atom_names` and `atom_types` in `append` function of `System`, if the `formula` of two systems are the same but either `atom_names` or `atom_types` is not equal
- Add unit tests for above
- Fix a bug in dpdata/deepmd/comp.py#L32, for `virs` may be `None`
> add MultiSystems and sort data when appending

- dpdata/system.py
- tests/gaussian/oxygen.gaussianlog
- tests/test_multisystems.py
Previous: `atom_types` of H2 and O2 are all `[0, 0]`
Now: `atom_types` of H2 and O2 are `[0, 0]` and `[1, 1]` respectively, so `dump_deepmd_npy` will dump correct `types.raw`.
> make atom_names in all systems equal

- dpdata/system.py
- tests/test_multisystems.py
including `__len__`, `__repr__`, `__str__`, `__add__`, and so on
```python
>>> import dpdata
>>> s1=dpdata.LabeledSystem("ch4_10s_0.6_H_00054.log", fmt="gaussian/log")
>>> s2=dpdata.LabeledSystem("ch4_10s_0.6_H_03070.log", fmt="gaussian/log")
>>> s3=dpdata.LabeledSystem("ch4_10s_0.6_H_08081.log", fmt="gaussian/log")
>>> m=dpdata.MultiSystems(s1)
>>> m
MultiSystems (1 systems containing 1 frames)
>>> m+=s2
>>> m
MultiSystems (2 systems containing 2 frames)
>>> m+s3
MultiSystems (3 systems containing 3 frames)
>>> len(m)
2
>>> for s in m:
...     print(s.formula)
...
C1H3O4
C0H5O3
```
also fix several bugs.
> enhance MultiSystems methods and bugfix

- dpdata/cp2k/output.py
change the sort method of atom_name
this bug will cause the fatal error when using dpgen 
Already tested and fixed by this new code.
please release to pip as soon as possible.
> preserve the output atom order

- dpdata/system.py
`System` obtained from `sub_system` should also follow the rule of data shape.
> fix sub_system data shape

- dpdata/deepmd/comp.py
- dpdata/deepmd/raw.py
- dpdata/gaussian/log.py
- dpdata/system.py
- tests/comp_sys.py
- tests/test_deepmd_comp.py
- tests/test_deepmd_raw.py
- tests/test_gaussian_log.py
- tests/test_json.py
- tests/test_lammps_dump_skipload.py
- tests/test_multisystems.py
- tests/test_perturb.py
- tests/test_qe_cp_traj_skipload.py
- tests/test_quip_gap_xyz.py
- tests/test_replicate.py
- tests/test_system_append.py
- tests/test_to_ase.py
- tests/test_to_list.py
- tests/test_to_pymatgen.py
- tests/test_vasp_outcar.py
- tests/test_vasp_poscar_to_system.py
- tests/test_vasp_xml.py
> support nopbc

- dpdata/system.py
the gaussian/log function has a parameter `md`, but there is no way to pass it.
https://github.com/deepmodeling/dpdata/blob/2dac5ffe9432d26d4bef3d85429c1e8c884d8fae/dpdata/gaussian/log.py#L13
fix this bug, add `**kwargs` in `__init__` of `class System`
> No way to pass parameter "md" in gaussian/log

- dpdata/cp2k/output.py
- tests/cp2k/cp2k_output
Fix the bug for double counting coordination information. 
The fp job which is stop once and restart in dpgen will print double head information. The cp2k parser will double count coordination information. 
A double head cp2k output is created to exam the robustness of parser
> fix double count bug

- dpdata/cp2k/output.py
- dpdata/system.py
- tests/cp2k/cp2k_output_2
- tests/cp2k/test.py
- fix the double cell information read from duplicated header case in cp2k.
- virial information of cp2k is not necessary thus, add the condition for check virial in system.py
- small example of how to use cp2k parser is also placed in `./test/cp2k/test.py`
> fix double cell bug and no virial information case

- dpdata/system.py
Add the ability to export energy, forces and virials to ASE atoms. It is implemented as **SinglePointCalculator** calculator which was designed to only remember results not to do any computations.
Now these methods can be used on exported **Atoms** object
```
Atoms.get_potential_energy()
Atoms.get_forces()
Atoms.get_stress()
```
The try except block in `System.to_ase_structure` method has been removed as it only catches the import error and the re-raises it and thus it provides no additional security.
> ASE enhance

- dpdata/vasp/outcar.py
- tests/poscars/OUTCAR.Ge.vdw
- tests/poscars/vasprun.Ge.vdw.xml
- tests/test_vasp_outcar.py
Forces are read incorrectly when `FORCE -w/o vdW` tag is output. When appropriate VASP prints this additional tag. The old read system thus read 6 force components for each atom. This failed when `LabeledSystem` tried to convert it to lower triangular
which was in this case multiplying matrices forces=(Nx6) x tranform(3x3)
```
POSITION                                       TOTAL-FORCE (eV/Angst),                                   FORCE-w/o vdW (eV/Angst)
--------------------------------------------------------------------------------------------------------
1.84643     -1.87564     13.81826        -0.056448      0.108946      0.296892        -0.056448      0.053966      0.296892
0.86824      2.31451      1.69518        -0.003983      0.006375      0.161565        -0.003983      0.006375 …
```
> fix bug in reading forces from OUTCAR

- dpdata/deepmd/comp.py
- dpdata/deepmd/raw.py
os.mknod method is not supported on MacOS and Windows.
See
https://stackoverflow.com/questions/32115715/os-mknod-fails-on-macos
Suggest use "with open" method
> Remove os.mknod in deepmd/{raw.py,comp.py}

- README.md
- dpdata/__init__.py
- dpdata/bond_order_system.py
- dpdata/cp2k/output.py
- dpdata/format.py
- dpdata/plugin.py
- dpdata/plugins/__init__.py
- dpdata/plugins/abacus.py
- dpdata/plugins/amber.py
- dpdata/plugins/ase.py
- dpdata/plugins/cp2k.py
- dpdata/plugins/deepmd.py
- dpdata/plugins/fhi_aims.py
- dpdata/plugins/gaussian.py
- dpdata/plugins/gromacs.py
- dpdata/plugins/lammps.py
- dpdata/plugins/list.py
- dpdata/plugins/pwmat.py
- dpdata/plugins/pymatgen.py
- dpdata/plugins/qe.py
- dpdata/plugins/rdkit.py
- dpdata/plugins/siesta.py
- dpdata/plugins/vasp.py
- dpdata/plugins/xyz.py
- dpdata/system.py
- plugin_example/README.md
- plugin_example/dpdata_random/__init__.py
- plugin_example/setup.py
- setup.py
- tests/test_bond_order_system.py
> refactor and add format plugin system

- .github/workflows/test.yml
- dpdata/plugins/pymatgen.py
- setup.py
> enable unittests of ase and pymatgen

- dpdata/deepmd/hdf5.py
- dpdata/plugins/deepmd.py
- setup.py
- tests/test_deepmd_hdf5.py
To support deepmodeling/deepmd-kit#1163.
> add deepmd/hdf5 format

- dpdata/plugins/xyz.py
- dpdata/xyz/xyz.py
- tests/test_xyz.py
This commit adds support for converting data to pure XYZ format. It's a quick way to visualize data using VMD or PyMol - these two software do support XYZ format file.
> add xyz format (to)

- dpdata/deepmd/hdf5.py
dpdata requires cells even in nopbc data.
> add default cells when loading hdf5 data

- dpdata/system.py
> add docstring to from/to method

- .gitignore
- docs/conf.py
- docs/formats.rst
- docs/index.rst
- docs/make_format.py
- dpdata/plugins/deepmd.py
- dpdata/plugins/qe.py
- dpdata/plugins/siesta.py
- dpdata/system.py
> generate formats table in doc

- dpdata/fhi_aims/output.py
- dpdata/rdkit/sanitize.py
- dpdata/unit.py
- tests/test_pick_atom_idx.py
- tests/test_to_ase.py
- tests/test_to_pymatgen.py
- tests/test_to_pymatgen_entry.py
- tests/test_water_ions.py
The latter will not catch `KeyboardInterrupt` and `SystemExit`. See https://stackoverflow.com/a/18982726/9567349.
> batch replace 'except:' with 'except Exception:'

- dpdata/amber/sqm.py
The code read the electronic energy (the following line of the total SCF energy) instead of the total SCF energy. This commit fixes it.
I have discussed with @Ericwang6. This should be the reason that our DP forces are good but DP energies are extremely bad.
> fix sqm energy

- dpdata/plugins/deepmd.py
The shape of energies should be (nframes,) instead of (nframes, 1)
> fix DP driver energy shape

- docs/conf.py
- dpdata/plugins/ase.py
- tests/test_to_ase.py
#190 added `from_labeled_system`, but it just passes a dict and does nothing else. This commit rewrites it.
> support converting ase.Atoms to System and LabeledSystem

- dpdata/deepmd/hdf5.py
- dpdata/plugins/deepmd.py
- tests/test_deepmd_hdf5.py
Now it is avoided to open the same file multiple times.
> refactor and optimize deepmd/hdf5 MultiSystems

- dpdata/bond_order_system.py
- dpdata/cp2k/output.py
- dpdata/plugins/ase.py
- dpdata/pwmat/atomconfig.py
- dpdata/pymatgen/molecule.py
- dpdata/system.py
- dpdata/xyz/quip_gap_xyz.py
- tests/comp_sys.py
* add DataType to manage types of data
* refactor data checking to check type and shape of data
** fix incorrect data type in some codes
* refactor methods including sub_system, append, sort_atom_types, shuffle, pick_atom_idx, and merge methods in LabeledSystem into those in System
> add data type; refactor methods

- dpdata/plugins/amber.py
> fix docs in #286

- .github/workflows/test.yml
Here we use `pip install` instead, as it's faster than `conda install`.
On the PyPI, `rdkit` package has been released officially. `openbabel-wheel` was made by me unofficially.
> drop conda in the test workflow

- dpdata/abacus/scf.py
- tests/abacus.scf/stru_test
- tests/test_abacus_md.py
One additional unit test has been added in the file "tests/test_abacus_md.py" to cover two functions for the abacus interface:
(1) "to_system" in dpdata/plugins/abacus.py
(2) "make_unlabeled_stru" in dpdata/abacus/scf.py
> test: add UT for to_system for abacus interface

- dpdata/abacus/scf.py
- tests/abacus.scf/INPUT
update input parameters in abacus.scf UT
> test: update input parameters in abacus.scf UT

- dpdata/system.py
See https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated. `np.int` is deprecated.
> replace deprecated np.int by int

- dpdata/vasp/outcar.py
> find the line index of viral in OUTCAR

- dpdata/fhi_aims/output.py
- dpdata/plugins/fhi_aims.py
- dpdata/plugins/pwmat.py
- dpdata/plugins/vasp.py
- dpdata/pwmat/movement.py
- dpdata/system.py
- dpdata/vasp/outcar.py
it is the realization for discussion #350.
> add option to ignore convergence check for `vasp/contcar`

- dpdata/plugins/3dmol.py
Example: https://nbviewer.org/gist/njzjz/14a638d1b5c85c1b2a4882418c34dd9d
> 3dmol format for visualization in jupyter

- pyproject.toml
Just realized that #366 requires setuptools>=61 and setuptools 59 has dropped Python 3.6.
> drop Python 3.6 support

- dpdata/system.py
`LabeledSystem.rot_lower_triangular` is the same as `System.rot_lower_triangular`. It's not necessary to define twice.
> remove duplicated rot_lower_triangular

- dpdata/system.py
The returned system should be of the same type as the perturbed system
> fix issue #381. 

- dpdata/abacus/scf.py
- tests/abacus.md.nostress/INPUT
- tests/abacus.md.unconv/INPUT
- tests/abacus.md/INPUT
- tests/abacus.relax/INPUT
- tests/abacus.scf/INPUT.fail
- tests/abacus.scf/INPUT.ok
The latest ABACUS 3.0.5 have removed the key word `ntype` in INPUT
> Fix: remove the reading of `ntype` in the parsing of abacus structure

- .pre-commit-config.yaml
- README.md
This PR adds a pre-commit hook to use Black to format Python codes in the documentation.
> format Python codes in docs

- pyproject.toml
The new version of parmed drops Python 3.7. However, it did not set `requires-python`, making pip on Python 3.7 still installs the latest version.
> pin parmed version for py37

- .git-blame-ignore-revs
See https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view
Note: it only works for `git blame` (or GitHub blame page) but does not work for `git history` (or GitHub file history page).
> add .git-blame-ignore-revs to hide formatting changes in git blame

- .pre-commit-config.yaml
- dpdata/amber/mask.py
- dpdata/amber/md.py
- dpdata/driver.py
- dpdata/format.py
- dpdata/md/rdf.py
- dpdata/plugin.py
- dpdata/plugins/abacus.py
- dpdata/plugins/deepmd.py
- dpdata/plugins/lammps.py
- dpdata/system.py
- dpdata/unit.py
- dpdata/xyz/xyz.py
Add a pre-commit hook to run automatic tools to follow the Numpydoc style guide.
> follow the numpydoc style guide

- README.md
- dpdata/deepmd/mixed.py
- dpdata/format.py
- dpdata/plugins/deepmd.py
- dpdata/system.py
- tests/test_deepmd_mixed.py
Add support for 'deepmd/mixed' format with dpdata.MultiSystems
1. Support dump from dpdata.MultiSystems to [mixed type format](https://github.com/deepmodeling/deepmd-kit/blob/master/doc/model/train-se-atten.md#data-format):
dpdata.MultiSystems.to_deepmd_mixed('dir_name_mixed')
2. Support load from mixed type format to dpdata.MultiSystems:
dpdata.MultiSystems.load_systems_from_file('dir_name_mixed', fmt='deepmd/mixed')
> Add support for 'deepmd/mixed' format with dpdata.MultiSystems

- dpdata/deepmd/mixed.py
- dpdata/format.py
- dpdata/plugins/deepmd.py
- dpdata/system.py
- tests/test_deepmd_mixed.py
This PR has concated two commits together:
1. Update the dpdata.MultiSystems() when from_deepmd_npy_mixed method is called;
dpdata.MultiSystems().from_deepmd_npy_mixed only returned the results before but did not change itself, which is fixed in this commit, to be consistent with other from methods. 
(another bug is also fixed: not using .copy() in data["atom_names"] may cause error when manually changing type_map for this system. UTs are added in the next commit.)
2. Allow multiple sets in mixed-type format;
Now for maximum 50000 frames in one sys and 2000 frames in one set.
The reason I did not use 5000 frames per set, is that I think maximum set frames will be much more often used in mixed-type format than other format, and 2000 will be enough for large batch and more friendly for …
> fix: standardize the deepmd/npy/mixed format

- dpdata/system.py
- tests/test_remove_outlier.py
Remove the outlier frames that satisfy 
$$
\frac{\left \| E - \bar{E} \right \|}{\sigma(E)} \geq \text{threshold}
$$
> add a method to remove outlier frames

- dpdata/qe/scf.py
From QE v7.2, pw.x prints each contributions to forces acting on atoms (i.e. non-local, ionic, local, core correction, etc...), right after original 'Forces acting on atoms' without blank line. Thus, it make 'list index out of range' error, from ret.append(...) in get_force.
This changes make length of list blk in get_forces same as total number of atoms, avoiding out of range error.
> Update for qe v7.2

- dpdata/system.py
- tests/test_split_dataset.py
Split a MultiSystems into training and test sub sets
> add train_test_split method

- dpdata/plugins/deepmd.py
Before this PR, when using DP models to predict energies and forces, the atom types were changed in the returned system according to the type map in the model. This is not an expected behavior. The changed atom types should only be used for internal inference.
> keep atom types when using DP models

- dpdata/deepmd/comp.py
- dpdata/deepmd/hdf5.py
- dpdata/deepmd/raw.py
- tests/test_custom_data_type.py
In this commit, the deepmd format reads data types from `dpdata.system.LabeledSystem.DTYPES` and load or dump the corresponding data. One can modify `dpdata.system.LabeledSystem.DTYPES` before using it or in a plugin (see tests), so deepmd format can be extended in this way.
> allow custom data types for deepmd format

- dpdata/abacus/scf.py
When using system.to() and convert data to write ABACUS `STRU` file, func `make_unlabeled_stru` won't use `atom_types` in data and miswriting the atom order. 
For example when using data from gaussian/log and other file using ungrouped atom coordinations,as the `atom_types=[0,1,1,1,2,1]` the func will write wrong coordinations and regard the atom as  `atom_types=[0,1,1,1,1,2]`  which cause serious problem.
> fix: writing abacus stru.

- dpdata/deepmd/hdf5.py
Follow up #476. `deepmd/npy` and `deepmd/raw` are ok, and only `deepmd/hdf5` has this bug.
> fix customized data shape in deepmd/hdf5

- .github/workflows/test.yml
- dpdata/data_type.py
- dpdata/system.py
- tests/plugin/dpdata_plugin_test/__init__.py
- tests/plugin/pyproject.toml
- tests/test_custom_data_type.py
Move DataType to an independent module, so register it will be eaiser. No breaking changes are made.
> add a public method to register new DataType in a plugin

- dpdata/driver.py
- dpdata/plugins/deepmd.py
- dpdata/system.py
> add extra lines for code blocks in docstring

- dpdata/system.py
- tests/test_custom_data_type.py
When a data type is unexpectedly registered twice, the behavior of some methods will be strange (for example, `append`).
For this reason, the old one is replaced, and a warning is thrown.
> replace the old data type with the same name and throw warning

- dpdata/system.py
- dpdata/utils.py
- tests/test_multisystems.py
> limit the filename length dumped by MultiSystems

- dpdata/plugins/psi4.py
- dpdata/psi4/output.py
The length conversion in Psi4 is not fixed to Bohr. Instead, the output unit follows the input unit and is written in the output file.
> fix psi4 length conversion

- dpdata/plugins/vasp.py
- tests/poscars/vasprun.h2o.md.novirial.xml
- tests/test_vasp_xml.py
> fix vasp/xml errors when no virial is printed

- dpdata/vasp/xml.py
- tests/poscars/vasprun.h2o.md.duplicate.xml
- tests/test_vasp_xml.py
Fix #480.
#250 doesn't handle this situation.
> fix duplicated elements in vasp/xml

- dpdata/qe/scf.py
`sys.exit` is a lousy implementation when one wants to catch the error.
> raise error instead of sys.exit

- dpdata/unit.py
fix issue https://github.com/deepmodeling/dpdata/issues/773
> fix: pin scipy constants to version 2018
