dpdata/gaussian/log.py, dpdata/system.py
第一个commit是修没有orig key的bug，修了这个bug才能跑通dpgen；第二个是防止Gaussian不收敛使dpdata报错，影响dpgen运行
=> bugfix: add 'orig' key for gaussian and prevent gaussian not converage

dpdata/deepmd/comp.py, dpdata/system.py
This is a draft. Do not merge.
=> dump atom_pref

dpdata/gaussian/log.py, dpdata/system.py
=> add gaussian/md

dpdata/siesta/aiMD_output.py, dpdata/siesta/output.py
=> fix_bug_siesta

dpdata/vasp/poscar.py
a bug costs me  three hours -----
=> fix bug for POSCAR format

dpdata/siesta/aiMD_output.py, dpdata/siesta/output.py
compatible siesta-4.0.2 and siesta-4.1-b4
=> compatible siesta-4.0.2 and siesta-4.1-b4

README.md, dpdata/system.py, tests/test_lammps_lmp_dump.py
register "from" and "to" functions, update documents
=> add experimental function register

dpdata/system.py
=> fix bug of to_ase_structure in #98

dpdata/vasp/outcar.py, tests/poscars/OUTCAR.Ge.vdw, tests/poscars/vasprun.Ge.vdw.xml, tests/test_vasp_outcar.py
merge changes of #132 with new CI.
=> Merge into master on behalf of marian

dpdata/system.py
which has a breaking change in the inference interface
=> support DP 2.x inference

dpdata/format.py, dpdata/plugins/deepmd.py, tests/test_multisystems.py
=> fix two bugs that implemented in #168

dpdata/deepmd/comp.py, dpdata/deepmd/raw.py, tests/comp_sys.py
=> fix loading nopbc system without box

dpdata/amber/sqm.py
the output forces are actually gradients
=> fix sqm/out forces

dpdata/driver.py, dpdata/plugins/deepmd.py, dpdata/system.py, tests/test_predict.py
A system will be able to be labeled by other drivers after they are implemented.
=> add driver plugin system framework; migrate DP predict to DPDriver

dpdata/unit.py
=> fix EnergyConversion example

dpdata/ase_calculator.py, dpdata/driver.py, dpdata/plugins/ase.py, tests/test_predict.py
This commit adds the ability to convert between dpdata driver and ase calculator.
- add a dpdata driver called `ASEDriver`
- add a ASE calculator called `DPDataCalculator`
=> dpdata driver <--> ase calculator

dpdata/gaussian/gjf.py, dpdata/plugins/gaussian.py, tests/context.py, tests/test_gaussian_driver.py
follow up #145... cc @Ericwang6 
Some codes are taken from dpgen. We may remove these codes from dpgen then..
=> add gaussian input format and driver

dpdata/plugins/ase.py
Adds `max_steps` parameter to `ASEMinimizer`.
=> support max_steps for ase minimizer

dpdata/cli.py, dpdata/deepmd/hdf5.py, dpdata/gaussian/gjf.py, dpdata/plugins/ase.py, dpdata/plugins/deepmd.py
Signed-off-by: Jinzhe Zeng <jinzhe.zeng@rutgers.edu>
=> add Optional to type hints when default is None

.github/workflows/test.yml
Same as https://github.com/deepmodeling/deepmd-kit/pull/2141
=> add pass step to GitHub Actions

README.md
=> docs: update installation commands

.readthedocs.yaml
per https://github.com/readthedocs/readthedocs.org/issues/10290#issuecomment-1535120995
=> fix RTD builds

.github/workflows/test.yml
Revert after https://github.com/materialsproject/pymatgen/issues/3166 is fixed.
=> pin pymatgen to 2023.7.11

.github/workflows/test.yml
Reverts deepmodeling/dpdata#501
Let's see if the error got fixed.
=> Revert "pin pymatgen to 2023.7.11"

.pre-commit-config.yaml, docs/make_format.py, dpdata/lammps/dump.py, pyproject.toml
See https://astral.sh/blog/the-ruff-formatter.
=> move to ruff formatter

MANIFEST.in
Per https://pypi.org/project/dpdata/0.2.17/#files, these files are too large.
=> exclude docs and tests from sdist

dpdata/gaussian/log.py, tests/gaussian/no_input_orient.gaussianlog, tests/test_gaussian_log.py
=> add error message when Gaussian input orientation is missing

dpdata/driver.py, tests/comp_sys.py, tests/test_predict.py
=> fix virial in HybridDriver

dpdata/system.py
Add function description on `system.py/check_type_map`
=> Add function description: apply_type_map

docs/conf.py, docs/environment.yml, docs/rtd_environment.yml, pyproject.toml
xref:
- https://github.com/emscripten-forge/recipes/issues/460
- https://xeus-python-kernel.readthedocs.io/en/latest/migration.html
=> docs: fix documentation build
